# Generated by Django 2.0.3 on 2018-03-13 04:11

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_photo', models.CharField(blank=True, default=None, max_length=200, verbose_name='наименование фото')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='product/photos', verbose_name='фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
            ],
            options={
                'verbose_name': 'фото товара',
                'verbose_name_plural': 'фотографии товара',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, verbose_name='наименование')),
                ('min_description', models.CharField(blank=True, default=None, max_length=400, verbose_name='мини описание')),
                ('description', models.TextField(blank=True, default=None, verbose_name='описание')),
                ('img', easy_thumbnails.fields.ThumbnailerImageField(upload_to='product/photos', verbose_name='фото')),
                ('prices', models.TextField(blank=True, default=0, verbose_name='цены')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=15, verbose_name='наименование')),
                ('name_model', models.CharField(blank=True, default=None, max_length=10, verbose_name='наименование Модели P')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'вид пиксиля',
                'verbose_name_plural': 'виды пиксиля',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product', verbose_name='Товар'),
        ),
    ]
