# Generated by Django 2.0.3 on 2018-03-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vid',
            field=models.ManyToManyField(to='stock.Vid'),
        ),
    ]
