# Generated by Django 2.0.3 on 2018-03-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vid',
        ),
        migrations.DeleteModel(
            name='Vid',
        ),
    ]
