# Generated by Django 2.0.3 on 2018-03-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180313_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=10, verbose_name='наименование P')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='цена')),
                ('vid', models.CharField(choices=[(1, 'Интерьерные'), (2, 'Уличный')], max_length=10, verbose_name='Вид эксплоатации')),
            ],
            options={
                'verbose_name': 'модель пиксиля',
                'verbose_name_plural': 'модели пиксиля',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
        migrations.AddField(
            model_name='pixel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product', verbose_name='Товар'),
        ),
    ]
