# Generated by Django 2.0.3 on 2018-03-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20180313_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixel',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default=23, verbose_name='цену'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pixel',
        ),
    ]
