# Generated by Django 2.0.3 on 2018-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_photo_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(blank=True, default='', verbose_name='price'),
        ),
    ]
