# Generated by Django 2.0.3 on 2018-03-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20180313_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_description',
        ),
    ]
