# Generated by Django 2.0.3 on 2018-03-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_product_min_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
