# Generated by Django 2.0.3 on 2018-03-10 13:49

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='название')),
                ('description', models.CharField(blank=True, default=None, max_length=500, verbose_name='описание')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='works/photos', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Протфолио',
                'verbose_name_plural': 'Портфолии',
                'ordering': ['name'],
            },
        ),
    ]
