# Generated by Django 2.0.3 on 2018-03-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['name'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
