# Generated by Django 2.0.3 on 2018-03-16 05:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0003_auto_20180313_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, verbose_name='описание'),
        ),
    ]
